import type { FinanceBlockConfig, SpendingBlockId } from './financeTypes.ts'

/**
 * ⚠️ CONTENT, GAME_ESTIMATE UNLESS NOTED (M6 §4-16, rebaselined M6.1 §5-7).
 * 9 controllable spending blocks — a reconciled GAMEPLAY decomposition of
 * the FRANCE 2027 BASELINE (`data/initialState.ts` /
 * `docs/FRANCE_BASELINE_2027.md`), not a literal COFOG/DREES accounting
 * split (M6 §6 explicitly warns against double-counting
 * pensions-vs-social-protection, cross-functional investment, and debt
 * interest inside "general services" — this file avoids all three by
 * construction: pensions and solidarity are separate blocks, investment
 * lives only in `economyInvestment`/`territories`, and debt interest is
 * NOT one of these blocks at all, see `financeEffects.ts`'s
 * `DEBT_INTEREST_BASELINE`).
 *
 * Baselines are anchored to commonly-cited real French functional-spending
 * orders of magnitude (Pensions ≈390 — COR-reported total pension
 * expenditure ≈14% GDP; Health ≈270 — ONDAM-scale; Défense 50 — the 2027
 * LPM 2024-2030 trajectory; the rest GAME_ESTIMATE envelopes sized to feel
 * plausible at this scale), NOT a blind proportional scale-up of the old
 * placeholder figures (M6.1 §5's explicit instruction) — administration
 * (233) is still the one block picked to close the sum exactly against
 * `primarySpending` (publicSpending 1,796 minus interestCost 76 = 1,720),
 * see the reconciliation test in `financeEffects.test.ts`.
 */
export const SPENDING_BLOCKS: Record<SpendingBlockId, FinanceBlockConfig<SpendingBlockId>> = {
  pensions: {
    id: 'pensions',
    label: 'Retraites',
    baseline: 390,
    provenance: 'GAME_ESTIMATE',
    tiers: [
      {
        id: 'protect',
        label: 'PROTÉGER LE SYSTÈME',
        annualFiscalDelta: 0,
        policyEffect: {},
        description: 'Maintien intégral du système actuel de retraites.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Aucun effet budgétaire supplémentaire.'],
        publicServiceEffects: ['Pouvoir d’achat des retraités inchangé.'],
        politicalTags: ['socialProtection'],
        promiseLinks: ['protect-pensions'],
      },
      {
        id: 'limitIndexation',
        label: 'LIMITER L’INDEXATION',
        annualFiscalDelta: -6,
        policyEffect: { transfersChanges: -6 },
        description: 'Ralentir la revalorisation des pensions par rapport à l’inflation.',
        implementationTiming: 2,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Amélioration progressive et modeste du déficit.'],
        publicServiceEffects: ['Érosion lente du pouvoir d’achat des retraités.'],
        politicalTags: ['fiscalDiscipline'],
        riskDescription: 'Mécontentement diffus chez les retraités.',
      },
      {
        id: 'targeted',
        label: 'RÉFORME CIBLÉE',
        annualFiscalDelta: -12,
        policyEffect: { transfersChanges: -12 },
        description: 'Ajustements ciblés (âge, régimes spéciaux) sans refonte générale.',
        implementationTiming: 3,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Économie budgétaire significative, différée.'],
        publicServiceEffects: ['Effet concentré sur certains régimes.'],
        politicalTags: ['fiscalDiscipline'],
        riskDescription: 'Contestation sociale modérée à élevée.',
      },
      {
        id: 'structural',
        label: 'RÉFORME STRUCTURELLE',
        annualFiscalDelta: -22,
        policyEffect: { transfersChanges: -22, laborMarketReform: 0.15 },
        description: 'Refonte structurelle du système de retraites (âge, calcul des pensions).',
        implementationTiming: 5,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Redressement durable des comptes publics, effet différé de plusieurs années.'],
        publicServiceEffects: ['Recul net du pouvoir d’achat des retraités concernés.'],
        politicalTags: ['fiscalDiscipline', 'reform'],
        riskDescription: 'Risque élevé de mobilisation sociale et de blocage du pays.',
      },
      {
        id: 'protectPurchasingPower',
        label: 'REVALORISER LES PENSIONS',
        annualFiscalDelta: 8,
        policyEffect: { transfersChanges: 8 },
        description: 'Revaloriser les pensions au-delà de l’inflation.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Soutien au pouvoir d’achat, coût budgétaire immédiat.'],
        publicServiceEffects: ['Hausse du pouvoir d’achat des retraités.'],
        politicalTags: ['socialProtection'],
        promiseLinks: ['protect-pensions'],
      },
    ],
  },

  health: {
    id: 'health',
    label: 'Santé',
    baseline: 270,
    provenance: 'GAME_ESTIMATE',
    tiers: [
      {
        id: 'efficiencyDrive',
        label: 'PLAN D’EFFICIENCE',
        annualFiscalDelta: -8,
        policyEffect: { currentSpendingChanges: -8 },
        description: 'Rationaliser les dépenses hospitalières sans fermer de services.',
        implementationTiming: 1,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Amélioration du déficit.'],
        publicServiceEffects: ['Pression accrue sur les personnels et les délais de soin.'],
        politicalTags: ['fiscalDiscipline'],
        riskDescription: 'Risque de grève hospitalière.',
      },
      {
        id: 'controlSpending',
        label: 'MAÎTRISER LA DÉPENSE',
        annualFiscalDelta: -3,
        policyEffect: { currentSpendingChanges: -3 },
        description: 'Un effort mesuré sur les dépenses de santé.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Léger effet positif sur le déficit.'],
        publicServiceEffects: ['Qualité de service quasi stable.'],
      },
      {
        id: 'maintain',
        label: 'MAINTIEN',
        annualFiscalDelta: 0,
        policyEffect: {},
        description: 'Maintien du budget santé actuel.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Aucun effet budgétaire supplémentaire.'],
        publicServiceEffects: ['Qualité de service stable.'],
      },
      {
        id: 'hospitalPlan',
        label: 'PLAN HÔPITAL',
        annualFiscalDelta: 10,
        policyEffect: { currentSpendingChanges: 10 },
        description: 'Renforcer durablement les moyens de l’hôpital public.',
        implementationTiming: 1,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Coût budgétaire immédiat.'],
        publicServiceEffects: ['Amélioration progressive de la qualité du service hospitalier.'],
        politicalTags: ['socialProtection'],
        promiseLinks: ['hospital-plan'],
      },
      {
        id: 'majorRebuild',
        label: 'GRAND PLAN HÔPITAL',
        annualFiscalDelta: 20,
        policyEffect: { currentSpendingChanges: 20 },
        description: 'Un plan massif de refondation de l’hôpital public.',
        implementationTiming: 2,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Coût budgétaire élevé, pèse durablement sur le déficit.'],
        publicServiceEffects: ['Amélioration marquée, mais progressive, de la qualité du service hospitalier.'],
        politicalTags: ['socialProtection'],
        promiseLinks: ['hospital-plan'],
      },
    ],
  },

  solidarity: {
    id: 'solidarity',
    label: 'Solidarité',
    baseline: 280,
    provenance: 'GAME_ESTIMATE',
    tiers: [
      {
        id: 'cuts',
        label: 'ÉCONOMIES',
        annualFiscalDelta: -10,
        policyEffect: { currentSpendingChanges: -10 },
        description: 'Réduire les minima sociaux et prestations familiales.',
        implementationTiming: 1,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Amélioration du déficit, pèse sur la demande des ménages modestes.'],
        publicServiceEffects: ['Recul de la protection sociale non-retraite.'],
        politicalTags: ['fiscalDiscipline'],
        riskDescription: 'Hausse de la tension sociale.',
      },
      {
        id: 'controlled',
        label: 'MAÎTRISÉ',
        annualFiscalDelta: -4,
        policyEffect: { currentSpendingChanges: -4 },
        description: 'Un effort mesuré sur les prestations sociales non-retraite.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Léger effet positif sur le déficit.'],
      },
      {
        id: 'maintain',
        label: 'MAINTIEN',
        annualFiscalDelta: 0,
        policyEffect: {},
        description: 'Maintien du budget solidarité actuel.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Aucun effet budgétaire supplémentaire.'],
      },
      {
        id: 'reinforce',
        label: 'RENFORCER',
        annualFiscalDelta: 8,
        policyEffect: { currentSpendingChanges: 8 },
        description: 'Renforcer les minima sociaux et prestations familiales.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Soutien à la demande des ménages modestes, coût budgétaire.'],
        publicServiceEffects: ['Réduction de la précarité.'],
        politicalTags: ['socialProtection'],
      },
      {
        id: 'majorPlan',
        label: 'GRAND PLAN DE SOLIDARITÉ',
        annualFiscalDelta: 16,
        policyEffect: { currentSpendingChanges: 16 },
        description: 'Un plan ambitieux de lutte contre la pauvreté.',
        implementationTiming: 1,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Coût budgétaire élevé, soutien marqué à la demande des ménages modestes.'],
        publicServiceEffects: ['Réduction sensible de la précarité.'],
        politicalTags: ['socialProtection'],
      },
    ],
  },

  education: {
    id: 'education',
    label: 'Éducation',
    baseline: 170,
    provenance: 'GAME_ESTIMATE',
    tiers: [
      {
        id: 'cuts',
        label: 'ÉCONOMIES',
        annualFiscalDelta: -8,
        policyEffect: { educationInvestment: -8 },
        description: 'Réduire les moyens de l’éducation nationale.',
        implementationTiming: 1,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Amélioration du déficit.', 'Pèse sur la productivité future (effet différé).'],
        publicServiceEffects: ['Dégradation progressive de la qualité du service éducatif.'],
        politicalTags: ['fiscalDiscipline'],
      },
      {
        id: 'controlled',
        label: 'MAÎTRISÉ',
        annualFiscalDelta: -3,
        policyEffect: { educationInvestment: -3 },
        description: 'Un effort mesuré sur le budget éducation.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Léger effet positif sur le déficit.'],
      },
      {
        id: 'maintain',
        label: 'MAINTIEN',
        annualFiscalDelta: 0,
        policyEffect: {},
        description: 'Maintien du budget éducation actuel.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Aucun effet budgétaire supplémentaire.'],
      },
      {
        id: 'invest',
        label: 'INVESTIR',
        annualFiscalDelta: 8,
        policyEffect: { educationInvestment: 8 },
        description: 'Investir dans l’école et l’enseignement supérieur.',
        implementationTiming: 2,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Coût budgétaire immédiat.', 'Bénéfice de productivité différé, modeste — pas de sursaut de croissance immédiat.'],
        publicServiceEffects: ['Amélioration progressive de la qualité du service éducatif.'],
        politicalTags: ['investment'],
        promiseLinks: ['invest-education'],
      },
    ],
  },

  economyInvestment: {
    id: 'economyInvestment',
    label: 'Économie & investissement',
    baseline: 165,
    provenance: 'GAME_ESTIMATE',
    tiers: [
      {
        id: 'cuts',
        label: 'ÉCONOMIES',
        annualFiscalDelta: -10,
        policyEffect: { publicInvestmentChanges: -10 },
        description: 'Réduire le soutien à l’économie et l’investissement public.',
        implementationTiming: 1,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Amélioration du déficit.', 'Pèse sur l’activité future.'],
        politicalTags: ['fiscalDiscipline'],
      },
      {
        id: 'maintain',
        label: 'MAINTIEN',
        annualFiscalDelta: 0,
        policyEffect: {},
        description: 'Maintien du soutien actuel à l’économie.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Aucun effet budgétaire supplémentaire.'],
      },
      {
        id: 'businessSupport',
        label: 'SOUTIEN AUX ENTREPRISES',
        annualFiscalDelta: 8,
        policyEffect: { currentSpendingChanges: 8 },
        description: 'Aides directes et dispositifs de soutien courant aux entreprises.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Soutien rapide à la confiance des entreprises, effet de croissance modeste.'],
        politicalTags: ['investment'],
      },
      {
        id: 'infrastructure',
        label: 'INFRASTRUCTURES',
        annualFiscalDelta: 14,
        policyEffect: { infrastructureInvestment: 14 },
        description: 'Investir dans les infrastructures de transport et d’énergie.',
        implementationTiming: 2,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Ne se finance jamais tout seul.', 'Bénéfice de productivité différé.'],
        politicalTags: ['investment'],
        promiseLinks: ['grand-investment-plan', 'energy-transition'],
      },
      {
        id: 'industryInnovation',
        label: 'INDUSTRIE & INNOVATION',
        annualFiscalDelta: 18,
        policyEffect: { researchInvestment: 18 },
        description: 'Co-investir dans l’industrie et l’innovation technologique.',
        implementationTiming: 2,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Coût budgétaire élevé.', 'Bénéfice de productivité différé, incertain.'],
        politicalTags: ['investment'],
        promiseLinks: ['grand-investment-plan'],
      },
    ],
  },

  defense: {
    id: 'defense',
    label: 'Défense',
    baseline: 50,
    provenance: 'GAME_ESTIMATE',
    tiers: [
      {
        id: 'cuts',
        label: 'ÉCONOMIES',
        annualFiscalDelta: -5,
        policyEffect: { currentSpendingChanges: -5 },
        description: 'Réduire les moyens des armées.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Amélioration du déficit.'],
        publicServiceEffects: ['Capacités militaires réduites.'],
      },
      {
        id: 'maintain',
        label: 'MAINTIEN',
        annualFiscalDelta: 0,
        policyEffect: {},
        description: 'Maintien du budget défense actuel.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Aucun effet budgétaire supplémentaire.'],
      },
      {
        id: 'moderateIncrease',
        label: 'AUGMENTATION MODÉRÉE',
        annualFiscalDelta: 6,
        policyEffect: { currentSpendingChanges: 6 },
        description: 'Renforcer modérément les moyens des armées.',
        implementationTiming: 1,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Coût budgétaire limité — pas d’effet de croissance notable.'],
        politicalTags: ['security'],
        promiseLinks: ['strengthen-defense'],
      },
      {
        id: 'majorIncrease',
        label: 'RÉARMEMENT',
        annualFiscalDelta: 14,
        policyEffect: { currentSpendingChanges: 14 },
        description: 'Un effort de réarmement significatif.',
        implementationTiming: 1,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Coût budgétaire élevé — pas de multiplicateur de croissance démesuré.'],
        politicalTags: ['security'],
        promiseLinks: ['strengthen-defense'],
      },
    ],
  },

  security: {
    id: 'security',
    label: 'Sécurité',
    baseline: 42,
    provenance: 'GAME_ESTIMATE',
    tiers: [
      {
        id: 'cuts',
        label: 'ÉCONOMIES',
        annualFiscalDelta: -4,
        policyEffect: { currentSpendingChanges: -4 },
        description: 'Réduire les moyens de la sécurité intérieure.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Amélioration du déficit.'],
        publicServiceEffects: ['Dégradation du service de sécurité.'],
      },
      {
        id: 'maintain',
        label: 'MAINTIEN',
        annualFiscalDelta: 0,
        policyEffect: {},
        description: 'Maintien du budget sécurité actuel.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Aucun effet budgétaire supplémentaire.'],
      },
      {
        id: 'reinforce',
        label: 'RENFORCER',
        annualFiscalDelta: 6,
        policyEffect: { currentSpendingChanges: 6 },
        description: 'Renforcer les effectifs et moyens de sécurité.',
        implementationTiming: 1,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Coût budgétaire modéré.'],
        publicServiceEffects: ['Amélioration progressive du service de sécurité.'],
        politicalTags: ['security'],
      },
      {
        id: 'majorPlan',
        label: 'GRAND PLAN SÉCURITÉ',
        annualFiscalDelta: 12,
        policyEffect: { currentSpendingChanges: 12 },
        description: 'Un plan ambitieux de renforcement de la sécurité intérieure.',
        implementationTiming: 1,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Coût budgétaire élevé.'],
        publicServiceEffects: ['Amélioration marquée du service de sécurité.'],
        politicalTags: ['security'],
      },
    ],
  },

  territories: {
    id: 'territories',
    label: 'Territoires, logement, environnement & culture',
    baseline: 120,
    provenance: 'GAME_ESTIMATE',
    tiers: [
      {
        id: 'cuts',
        label: 'ÉCONOMIES',
        annualFiscalDelta: -6,
        policyEffect: { currentSpendingChanges: -6 },
        description: 'Réduire les dotations aux territoires et les politiques du logement/de l’environnement/de la culture.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Amélioration du déficit.'],
      },
      {
        id: 'maintain',
        label: 'MAINTIEN',
        annualFiscalDelta: 0,
        policyEffect: {},
        description: 'Maintien du budget actuel.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Aucun effet budgétaire supplémentaire.'],
      },
      {
        id: 'housingPriority',
        label: 'PRIORITÉ LOGEMENT',
        annualFiscalDelta: 8,
        policyEffect: { publicInvestmentChanges: 8 },
        description: 'Un plan de construction et de rénovation de logements.',
        implementationTiming: 2,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Coût budgétaire, soutien différé à l’activité du bâtiment.'],
        politicalTags: ['investment'],
        promiseLinks: ['build-housing'],
      },
      {
        id: 'greenPriority',
        label: 'PRIORITÉ VERTE',
        annualFiscalDelta: 8,
        policyEffect: { infrastructureInvestment: 8 },
        description: 'Accélérer la transition environnementale des territoires.',
        implementationTiming: 2,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Coût budgétaire, bénéfice différé.'],
        politicalTags: ['environment', 'investment'],
        promiseLinks: ['energy-transition'],
      },
      {
        id: 'territorialInvestment',
        label: 'INVESTISSEMENT TERRITORIAL',
        annualFiscalDelta: 6,
        policyEffect: { currentSpendingChanges: 6 },
        description: 'Renforcer les dotations directes aux collectivités territoriales.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Coût budgétaire, soutien direct aux services locaux.'],
      },
    ],
  },

  administration: {
    id: 'administration',
    label: 'Administration',
    baseline: 233,
    provenance: 'GAME_ESTIMATE',
    tiers: [
      {
        id: 'maintain',
        label: 'MAINTIEN',
        annualFiscalDelta: 0,
        policyEffect: {},
        description: 'Maintien du fonctionnement actuel de l’administration.',
        implementationTiming: 0,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Aucun effet budgétaire supplémentaire.'],
      },
      {
        id: 'efficiencyProgram',
        label: 'PROGRAMME D’EFFICIENCE',
        annualFiscalDelta: -5,
        policyEffect: { currentSpendingChanges: -5, publicSectorReform: 0.2 },
        description: 'Rationaliser les dépenses de fonctionnement de l’État.',
        implementationTiming: 2,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Amélioration progressive du déficit.'],
        publicServiceEffects: ['Légère pression sur le service administratif.'],
        politicalTags: ['fiscalDiscipline'],
      },
      {
        id: 'digitalization',
        label: 'DIGITALISATION & MODERNISATION',
        annualFiscalDelta: -3,
        policyEffect: { currentSpendingChanges: -3, publicSectorReform: 0.35 },
        description: 'Moderniser l’administration : un coût initial, des économies récurrentes différées.',
        implementationTiming: 3,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Coût de mise en œuvre initial, économies nettes seulement après quelques années.'],
        publicServiceEffects: ['Amélioration possible du service à moyen terme.'],
        politicalTags: ['reform'],
      },
      {
        id: 'deepCuts',
        label: 'PLAN DRASTIQUE',
        annualFiscalDelta: -12,
        policyEffect: { currentSpendingChanges: -12 },
        description: 'Réduction drastique du train de vie de l’État.',
        implementationTiming: 1,
        temporaryOrPermanent: 'PERMANENT',
        economicEffects: ['Amélioration marquée et rapide du déficit.'],
        publicServiceEffects: ['Dégradation sensible du service administratif.'],
        politicalTags: ['fiscalDiscipline'],
        riskDescription: 'Risque social élevé et perte de qualité de service.',
      },
    ],
  },
}

export const SPENDING_BLOCK_ORDER: SpendingBlockId[] = [
  'pensions',
  'health',
  'solidarity',
  'education',
  'economyInvestment',
  'defense',
  'security',
  'territories',
  'administration',
]

export function getSpendingTier(blockId: SpendingBlockId, tierId: string) {
  const tier = SPENDING_BLOCKS[blockId].tiers.find((t) => t.id === tierId)
  if (!tier) throw new Error(`Unknown tier "${tierId}" for spending block "${blockId}"`)
  return tier
}

/** Every spending block's "no change from baseline" tier — the mandate's first budget cycle drafts from here. */
export const NEUTRAL_SPENDING_LEVELS: Record<SpendingBlockId, string> = {
  pensions: 'protect',
  health: 'maintain',
  solidarity: 'maintain',
  education: 'maintain',
  economyInvestment: 'maintain',
  defense: 'maintain',
  security: 'maintain',
  territories: 'maintain',
  administration: 'maintain',
}
