import { ABSOLUTE_MAJORITY } from '../prototype/parliament.ts'
import type { PoliticalBillDefinition } from './billTypes.ts'

/**
 * ⚠️ PROTOTYPE CONTENT (M4 §30-31, expanded to 12 in M5 §36). The
 * discretionary "Conseil des Ministres" bills — the player brings forward
 * at most ONE per gameplay year (M5 §35), in addition to that year's
 * mandatory Budget Bill (derived at runtime by `budgetBillDerivation.ts`,
 * not listed here since it depends on the player's actual Budget Builder
 * choices rather than being static content). Every fiscal/political
 * number is a gameplay-design choice, not sourced. Not every reform is
 * beneficial (M5 §37) — several trade a real fiscal saving or structural
 * benefit for high controversy and a real chance of provoking a social
 * protest event.
 */
export const BILL_CATALOG: PoliticalBillDefinition[] = [
  {
    id: 'hospital-plan-bill',
    title: 'PLAN HÔPITAL',
    description: 'Renforcer durablement les moyens de l’hôpital public.',
    policyTags: { health: 0.9, publicSpending: 0.4 },
    economicPolicyEffect: { currentSpendingChanges: 10 },
    fiscalCost: 10,
    reformIntensity: 0.3,
    controversy: 0.15,
    promiseLinks: ['hospital-plan'],
    requiredPoliticalCapital: 6,
    urgency: 'MEDIUM',
    negotiability: 0.7,
    concessionsAvailable: ['INCREASE_HEALTH_FUNDING', 'INCREASE_TERRITORIAL_SUPPORT', 'REDUCE_SPENDING_CAP'],
    voteThreshold: ABSOLUTE_MAJORITY,
    implementationDelay: 1,
  },
  {
    id: 'education-investment-bill',
    title: 'INVESTISSEMENT ÉDUCATION',
    description: 'Investir durablement dans l’école et l’enseignement supérieur.',
    policyTags: { education: 0.9, publicInvestment: 0.3 },
    economicPolicyEffect: { educationInvestment: 8 },
    fiscalCost: 8,
    reformIntensity: 0.3,
    controversy: 0.1,
    promiseLinks: ['invest-education'],
    requiredPoliticalCapital: 5,
    urgency: 'MEDIUM',
    negotiability: 0.75,
    concessionsAvailable: ['INCREASE_TERRITORIAL_SUPPORT', 'REDUCE_SPENDING_CAP'],
    voteThreshold: ABSOLUTE_MAJORITY,
    implementationDelay: 1,
  },
  {
    id: 'business-tax-cut-bill',
    title: 'BAISSE DE LA FISCALITÉ DES ENTREPRISES',
    description: 'Réduire la fiscalité pesant sur les entreprises pour soutenir l’investissement.',
    policyTags: { businessTax: -0.8, fiscalDiscipline: -0.2 },
    economicPolicyEffect: { businessTaxImpulse: -6 },
    fiscalCost: 6,
    reformIntensity: 0.4,
    controversy: 0.35,
    promiseLinks: ['cut-business-taxes'],
    requiredPoliticalCapital: 10,
    urgency: 'MEDIUM',
    negotiability: 0.6,
    concessionsAvailable: ['REDUCE_SPENDING_CAP', 'INCREASE_TERRITORIAL_SUPPORT'],
    voteThreshold: ABSOLUTE_MAJORITY,
    implementationDelay: 1,
  },
  {
    id: 'energy-transition-bill',
    title: 'TRANSITION ÉNERGÉTIQUE',
    description: 'Accélérer l’investissement dans la transition énergétique.',
    policyTags: { environment: 0.9, publicInvestment: 0.5 },
    economicPolicyEffect: { publicInvestmentChanges: 8 },
    fiscalCost: 8,
    reformIntensity: 0.5,
    controversy: 0.3,
    promiseLinks: ['energy-transition'],
    requiredPoliticalCapital: 9,
    urgency: 'MEDIUM',
    negotiability: 0.65,
    concessionsAvailable: ['INCREASE_GREEN_INVESTMENT', 'INCREASE_TERRITORIAL_SUPPORT', 'REDUCE_SPENDING_CAP'],
    voteThreshold: ABSOLUTE_MAJORITY,
    implementationDelay: 2,
  },
  {
    id: 'household-tax-cut-bill',
    title: 'BAISSE DE LA FISCALITÉ DES MÉNAGES',
    description: 'Réduire l’impôt qui pèse sur le travail et les ménages.',
    policyTags: { householdTax: -0.8, publicSpending: -0.1 },
    economicPolicyEffect: { householdTaxImpulse: -6 },
    fiscalCost: 6,
    reformIntensity: 0.3,
    controversy: 0.3,
    promiseLinks: ['cut-household-taxes'],
    requiredPoliticalCapital: 9,
    urgency: 'MEDIUM',
    negotiability: 0.6,
    concessionsAvailable: ['REDUCE_SPENDING_CAP', 'INCREASE_TERRITORIAL_SUPPORT'],
    voteThreshold: ABSOLUTE_MAJORITY,
    implementationDelay: 1,
  },
  {
    id: 'housing-construction-plan-bill',
    title: 'PLAN DE CONSTRUCTION DE LOGEMENTS',
    description: 'Soutenir massivement la construction de logements neufs.',
    policyTags: { housing: 0.9, publicInvestment: 0.4 },
    economicPolicyEffect: { publicInvestmentChanges: 8 },
    fiscalCost: 8,
    reformIntensity: 0.4,
    controversy: 0.2,
    promiseLinks: ['build-housing'],
    requiredPoliticalCapital: 7,
    urgency: 'MEDIUM',
    negotiability: 0.7,
    concessionsAvailable: ['INCREASE_HOUSING_FUNDING', 'INCREASE_TERRITORIAL_SUPPORT'],
    voteThreshold: ABSOLUTE_MAJORITY,
    implementationDelay: 2,
  },
  {
    id: 'pension-reform-bill',
    title: 'RÉFORME DES RETRAITES',
    description: 'Ralentir la progression des dépenses de retraite pour redresser les comptes publics.',
    policyTags: { pensions: -0.7, fiscalDiscipline: 0.5, laborMarket: 0.2 },
    economicPolicyEffect: { transfersChanges: -8 },
    fiscalCost: -8,
    reformIntensity: 0.8,
    controversy: 0.85,
    promiseLinks: ['reduce-deficit', 'reduce-debt'],
    requiredPoliticalCapital: 20,
    urgency: 'LOW',
    negotiability: 0.4,
    concessionsAvailable: ['REDUCE_SPENDING_CAP'],
    voteThreshold: ABSOLUTE_MAJORITY,
    implementationDelay: 3,
  },
  {
    id: 'labor-market-reform-bill',
    title: 'RÉFORME DU MARCHÉ DU TRAVAIL',
    description: 'Assouplir les règles du marché du travail pour soutenir l’emploi.',
    policyTags: { laborMarket: 0.8, publicSpending: -0.1 },
    economicPolicyEffect: { laborMarketReform: 0.6 },
    fiscalCost: 0,
    reformIntensity: 0.7,
    controversy: 0.55,
    promiseLinks: ['reduce-unemployment'],
    requiredPoliticalCapital: 14,
    urgency: 'MEDIUM',
    negotiability: 0.5,
    concessionsAvailable: ['REDUCE_SPENDING_CAP', 'INCREASE_TERRITORIAL_SUPPORT'],
    voteThreshold: ABSOLUTE_MAJORITY,
    implementationDelay: 2,
  },
  {
    id: 'public-administration-reform-bill',
    title: 'RÉFORME DE L’ADMINISTRATION',
    description: 'Réorganiser l’administration pour en améliorer l’efficacité.',
    policyTags: { fiscalDiscipline: 0.6, publicSpending: -0.4 },
    economicPolicyEffect: { publicSectorReform: 0.5, currentSpendingChanges: -6 },
    fiscalCost: -6,
    reformIntensity: 0.5,
    controversy: 0.45,
    promiseLinks: [],
    requiredPoliticalCapital: 10,
    urgency: 'LOW',
    negotiability: 0.6,
    concessionsAvailable: ['REDUCE_SPENDING_CAP'],
    voteThreshold: ABSOLUTE_MAJORITY,
    implementationDelay: 2,
  },
  {
    id: 'defense-expansion-bill',
    title: 'EXPANSION DE LA DÉFENSE',
    description: 'Renforcer durablement les moyens des armées.',
    policyTags: { defense: 0.9, publicSpending: 0.2 },
    economicPolicyEffect: { currentSpendingChanges: 10 },
    fiscalCost: 10,
    reformIntensity: 0.3,
    controversy: 0.25,
    promiseLinks: ['strengthen-defense'],
    requiredPoliticalCapital: 8,
    urgency: 'MEDIUM',
    negotiability: 0.65,
    concessionsAvailable: ['REDUCE_SPENDING_CAP', 'INCREASE_TERRITORIAL_SUPPORT'],
    voteThreshold: ABSOLUTE_MAJORITY,
    implementationDelay: 1,
  },
  {
    id: 'industry-innovation-plan-bill',
    title: 'PLAN INDUSTRIE ET INNOVATION',
    description: 'Co-investir dans l’industrie et l’innovation technologique.',
    policyTags: { publicInvestment: 0.8, businessTax: -0.2 },
    economicPolicyEffect: { researchInvestment: 8, businessTaxImpulse: -2 },
    fiscalCost: 10,
    reformIntensity: 0.4,
    controversy: 0.2,
    promiseLinks: ['grand-investment-plan'],
    requiredPoliticalCapital: 8,
    urgency: 'MEDIUM',
    negotiability: 0.7,
    concessionsAvailable: ['INCREASE_GREEN_INVESTMENT', 'INCREASE_TERRITORIAL_SUPPORT'],
    voteThreshold: ABSOLUTE_MAJORITY,
    implementationDelay: 2,
  },
  {
    id: 'public-investment-plan-bill',
    title: 'GRAND PLAN D’INVESTISSEMENT PUBLIC',
    description: 'Lancer un grand plan d’investissement dans les infrastructures.',
    policyTags: { publicInvestment: 0.9, fiscalDiscipline: -0.3 },
    economicPolicyEffect: { publicInvestmentChanges: 15, infrastructureInvestment: 5 },
    fiscalCost: 20,
    reformIntensity: 0.5,
    controversy: 0.35,
    promiseLinks: ['grand-investment-plan'],
    requiredPoliticalCapital: 12,
    urgency: 'MEDIUM',
    negotiability: 0.6,
    concessionsAvailable: ['REDUCE_SPENDING_CAP', 'INCREASE_TERRITORIAL_SUPPORT'],
    voteThreshold: ABSOLUTE_MAJORITY,
    implementationDelay: 2,
  },
]

export function getBillDefinition(id: string): PoliticalBillDefinition {
  const bill = BILL_CATALOG.find((b) => b.id === id)
  if (!bill) throw new Error(`Unknown bill: ${id}`)
  return bill
}
