import type { EventDefinition } from './eventTypes.ts'

/**
 * ⚠️ PROTOTYPE CONTENT (M5 §8, §11-22). 13 definitions covering 12
 * conceptual events (`tax-windfall`/`tax-shortfall` are the two
 * condition-gated variants of ONE "tax revenue surprise" event, mutually
 * exclusive by their opposite `conditions`). No real French party or a
 * literal real-world future event — France's starting point is
 * real-inspired, the mandate's future is entirely fictional. Every
 * fiscal/political number is a gameplay-design choice, not sourced.
 */
export const EVENT_CATALOG: EventDefinition[] = [
  {
    id: 'energy-shock',
    title: 'LE PÉTROLE BONDIT',
    category: 'ENERGY',
    description: 'Une crise internationale provoque une hausse brutale des prix de l’énergie. Les ménages et les entreprises commencent à ressentir le choc.',
    earliestTurn: 1,
    latestTurn: 12,
    baseProbability: 0.3,
    worldShock: {
      id: 'energy-shock-mandate',
      world: { oilPriceIndex: 28 },
      directGrowthEffect: -0.3,
      confidence: { consumerConfidence: -5, businessConfidence: -3 },
    },
    choices: [
      {
        id: 'broad-shield',
        title: 'BOUCLIER ÉNERGÉTIQUE LARGE',
        description: 'Un soutien général au pouvoir d’achat, coûteux mais large.',
        fiscalEffect: 15,
        economicPolicyEffect: { transfersChanges: 15 },
        popularityEffect: 3,
        immediateFeedback: '+15 Md€/an de soutien général au pouvoir d’achat.',
      },
      {
        id: 'targeted-support',
        title: 'AIDE CIBLÉE',
        description: 'Une aide plus modeste, ciblée sur les ménages modestes.',
        fiscalEffect: 6,
        economicPolicyEffect: { transfersChanges: 6 },
        popularityEffect: 1.5,
        immediateFeedback: '+6 Md€/an, ciblé sur les ménages modestes.',
      },
      {
        id: 'no-intervention',
        title: 'AUCUNE INTERVENTION',
        description: 'Laisser les prix s’ajuster.',
        popularityEffect: -3,
        immediateFeedback: 'Aucun coût budgétaire, mais le pouvoir d’achat encaisse le choc.',
      },
    ],
  },
  {
    id: 'hospital-strike',
    title: 'LES URGENCES SE METTENT EN GRÈVE',
    category: 'PUBLIC_SERVICES',
    description: 'Le personnel hospitalier se met en grève pour dénoncer le manque de moyens.',
    earliestTurn: 3,
    latestTurn: 24,
    baseProbability: 0.12,
    probabilityModifier: (ctx) => {
      const healthCut = ctx.policyHistory.some((e) => e.category === 'health' && (e.amount ?? 0) < 0)
      return healthCut ? 2.2 : 1
    },
    choices: [
      {
        id: 'emergency-package',
        title: 'PLAN D’URGENCE HOSPITALIER',
        description: 'Un financement d’urgence pour les hôpitaux publics.',
        fiscalEffect: 6,
        economicPolicyEffect: { currentSpendingChanges: 6 },
        popularityEffect: 2,
        politicalCapitalEffect: 2,
        immediateFeedback: '+6 Md€/an d’urgence pour l’hôpital.',
      },
      {
        id: 'negotiate-limited',
        title: 'NÉGOCIER SANS FINANCEMENT MAJEUR',
        description: 'Un compromis limité avec les syndicats.',
        fiscalEffect: 2,
        economicPolicyEffect: { currentSpendingChanges: 2 },
        immediateFeedback: '+2 Md€/an, un compromis limité.',
      },
      {
        id: 'hold-firm',
        title: 'TENIR BON',
        description: 'Ne rien céder.',
        popularityEffect: -3,
        politicalCapitalEffect: -3,
        governmentTensionEffect: 4,
        immediateFeedback: 'Aucune concession — la grève se prolonge.',
        riskDescription: 'Risque de contestation sociale plus large.',
      },
    ],
  },
  {
    id: 'plant-closure',
    title: 'UNE GRANDE USINE ANNONCE SA FERMETURE',
    category: 'INDUSTRY',
    description: 'Un grand site industriel annonce sa fermeture, menaçant des milliers d’emplois.',
    earliestTurn: 4,
    latestTurn: 26,
    baseProbability: 0.1,
    choices: [
      {
        id: 'support-package',
        title: 'PLAN DE SOUTIEN PUBLIC',
        description: 'Un soutien financier direct au site et à ses salariés.',
        fiscalEffect: 5,
        economicPolicyEffect: { currentSpendingChanges: 5 },
        popularityEffect: 1.5,
        immediateFeedback: '+5 Md€/an de soutien direct.',
      },
      {
        id: 'regional-investment',
        title: 'INVESTISSEMENT RÉGIONAL',
        description: 'Un plan de reconversion régionale, dont l’effet prend du temps à se matérialiser.',
        fiscalEffect: 6,
        delayedEffects: [{ turnsLater: 3, policyEffect: { publicInvestmentChanges: 6 } }],
        popularityEffect: 0.5,
        immediateFeedback: 'Un plan d’investissement régional se met en place — effet visible dans quelques mois.',
      },
      {
        id: 'no-intervention',
        title: 'NE PAS INTERVENIR',
        description: 'Laisser faire.',
        popularityEffect: -2.5,
        immediateFeedback: 'Aucun coût budgétaire, mais un choc local sur l’emploi et la confiance des entreprises.',
      },
    ],
  },
  {
    id: 'european-slowdown',
    title: 'L’EUROPE ENTRE EN RALENTISSEMENT',
    category: 'INTERNATIONAL',
    description: 'La croissance ralentit dans plusieurs grandes économies européennes, pesant sur le commerce extérieur.',
    earliestTurn: 5,
    latestTurn: 22,
    baseProbability: 0.1,
    worldShock: { id: 'european-slowdown-shock', world: { eurozoneGrowth: -1.2, globalTradeGrowth: -0.8 } },
    choices: [
      {
        id: 'soften-domestic',
        title: 'AMORTIR L’IMPACT INTÉRIEUR',
        description: 'Un soutien à l’activité domestique — le choc externe reste réel.',
        fiscalEffect: 5,
        economicPolicyEffect: { publicInvestmentChanges: 5 },
        popularityEffect: 1,
        immediateFeedback: '+5 Md€/an pour soutenir l’activité domestique — le ralentissement européen, lui, reste hors de votre contrôle.',
      },
      {
        id: 'wait-and-see',
        title: 'LAISSER PASSER',
        description: 'Aucune réponse budgétaire.',
        popularityEffect: -1,
        immediateFeedback: 'Aucune réponse budgétaire — la France suit le ralentissement européen.',
      },
    ],
  },
  {
    id: 'drought-shock',
    title: 'UNE SÉCHERESSE HISTORIQUE FRAPPE LE PAYS',
    category: 'CLIMATE',
    description: 'Une sécheresse exceptionnelle pèse sur l’agriculture, l’énergie et les prix.',
    earliestTurn: 6,
    latestTurn: 28,
    baseProbability: 0.08,
    worldShock: { id: 'drought-shock', directGrowthEffect: -0.15, confidence: { consumerConfidence: -3 } },
    choices: [
      {
        id: 'emergency-support',
        title: 'SOUTIEN D’URGENCE',
        description: 'Une aide immédiate aux ménages et agriculteurs touchés.',
        fiscalEffect: 5,
        economicPolicyEffect: { transfersChanges: 5 },
        popularityEffect: 1.5,
        immediateFeedback: '+5 Md€/an de soutien d’urgence.',
      },
      {
        id: 'accelerate-adaptation',
        title: 'ACCÉLÉRER L’ADAPTATION',
        description: 'Investir dans l’adaptation climatique — lié à la transition énergétique.',
        fiscalEffect: 6,
        economicPolicyEffect: { infrastructureInvestment: 6 },
        popularityEffect: 1,
        immediateFeedback: '+6 Md€/an d’investissement dans l’adaptation climatique.',
      },
      {
        id: 'limited-response',
        title: 'RÉPONSE LIMITÉE',
        description: 'Une réponse minimale.',
        popularityEffect: -2,
        immediateFeedback: 'Réponse minimale — la confiance des ménages en pâtit.',
      },
    ],
  },
  {
    id: 'housing-crisis',
    title: 'LA CRISE DU LOGEMENT S’AGGRAVE',
    category: 'HOUSING',
    description: 'La construction ralentit et l’accès au logement se dégrade.',
    earliestTurn: 4,
    latestTurn: 24,
    baseProbability: 0.08,
    probabilityModifier: (ctx) => {
      const promisedHousing = ctx.selectedPromiseIds.includes('build-housing')
      const investedInHousing = ctx.policyHistory.some((e) => (e.category === 'housing' || e.category === 'investment') && (e.amount ?? 0) > 0)
      return promisedHousing && !investedInHousing ? 2 : 1
    },
    choices: [
      {
        id: 'investment-plan',
        title: 'PLAN D’INVESTISSEMENT LOGEMENT',
        description: 'Un plan de construction financé directement.',
        fiscalEffect: 6,
        economicPolicyEffect: { publicInvestmentChanges: 6 },
        popularityEffect: 1.5,
        immediateFeedback: '+6 Md€/an pour la construction.',
      },
      {
        id: 'rental-support',
        title: 'AIDE AUX LOCATAIRES',
        description: 'Une aide directe aux ménages locataires.',
        fiscalEffect: 4,
        economicPolicyEffect: { transfersChanges: 4 },
        popularityEffect: 1,
        immediateFeedback: '+4 Md€/an d’aide directe.',
      },
      {
        id: 'regulatory-reform',
        title: 'RÉFORME RÉGLEMENTAIRE',
        description: 'Simplifier les règles de construction — l’effet met du temps à se matérialiser.',
        delayedEffects: [{ turnsLater: 3, policyEffect: { publicInvestmentChanges: 3 } }],
        popularityEffect: 0.5,
        immediateFeedback: 'Une réforme réglementaire dont l’effet se fera sentir progressivement.',
      },
    ],
  },
  {
    id: 'debt-warning',
    title: 'LES MARCHÉS S’INQUIÈTENT DE LA DETTE FRANÇAISE',
    category: 'ECONOMY',
    description: 'Les investisseurs commencent à s’inquiéter de la trajectoire des finances publiques françaises.',
    earliestTurn: 6,
    latestTurn: 28,
    baseProbability: 0.1,
    conditions: (ctx) => ctx.gameState.economic.debtRatio > 122 || ctx.gameState.economic.deficitRatio > 5.5 || ctx.gameState.economic.marketConfidence < 42,
    choices: [
      {
        id: 'consolidation-plan',
        title: 'ANNONCER UN PLAN DE CONSOLIDATION',
        description: 'Un signal de sérieux budgétaire envoyé aux marchés.',
        fiscalEffect: -6,
        economicPolicyEffect: { currentSpendingChanges: -6 },
        popularityEffect: -1.5,
        immediateFeedback: '-6 Md€/an — un signal de sérieux budgétaire aux marchés.',
      },
      {
        id: 'maintain-strategy',
        title: 'MAINTENIR LE CAP',
        description: 'Ne rien changer.',
        popularityEffect: 0.5,
        immediateFeedback: 'Aucun changement — les marchés restent attentifs.',
      },
      {
        id: 'emergency-freeze',
        title: 'GEL BUDGÉTAIRE D’URGENCE',
        description: 'Un effort brutal et immédiat.',
        fiscalEffect: -12,
        economicPolicyEffect: { currentSpendingChanges: -12 },
        popularityEffect: -3,
        governmentTensionEffect: 3,
        immediateFeedback: '-12 Md€/an — fort effet sur la confiance des marchés, coût politique réel.',
      },
    ],
  },
  {
    id: 'social-protest',
    title: 'LA CONTESTATION GAGNE LE PAYS',
    category: 'SOCIAL',
    description: 'Un mouvement de contestation sociale prend de l’ampleur.',
    earliestTurn: 5,
    latestTurn: 27,
    baseProbability: 0.09,
    probabilityModifier: (ctx) => {
      const heavyCuts = ctx.policyHistory.filter((e) => (e.amount ?? 0) < -8).length
      const highUnemployment = ctx.gameState.economic.unemployment > 8.5
      return 1 + heavyCuts * 0.4 + (highUnemployment ? 0.5 : 0)
    },
    choices: [
      {
        id: 'concede',
        title: 'CÉDER',
        description: 'Des concessions budgétaires substantielles.',
        fiscalEffect: 5,
        economicPolicyEffect: { transfersChanges: 5 },
        popularityEffect: 2,
        politicalCapitalEffect: -3,
        immediateFeedback: '+5 Md€/an de concessions.',
      },
      {
        id: 'negotiate',
        title: 'NÉGOCIER',
        description: 'Un compromis limité.',
        popularityEffect: 0.5,
        politicalCapitalEffect: -1,
        immediateFeedback: 'Un compromis limité, sans coût budgétaire majeur.',
      },
      {
        id: 'hold-firm',
        title: 'TENIR BON',
        description: 'Ne rien céder.',
        popularityEffect: -4,
        governmentTensionEffect: 6,
        immediateFeedback: 'Aucune concession — la tension sociale et politique monte.',
        riskDescription: 'Risque d’escalade de la contestation.',
      },
    ],
  },
  {
    id: 'ai-industry-plan',
    title: 'UN PLAN EUROPÉEN POUR L’IA ET L’INDUSTRIE',
    category: 'INDUSTRY',
    description: 'L’Union européenne propose un grand plan de co-investissement dans l’intelligence artificielle et l’industrie.',
    earliestTurn: 8,
    latestTurn: 26,
    baseProbability: 0.09,
    choices: [
      {
        id: 'large-co-investment',
        title: 'CO-INVESTISSEMENT IMPORTANT',
        description: 'Un engagement fort — effet de productivité différé, comme tout investissement en recherche.',
        fiscalEffect: 6,
        economicPolicyEffect: { researchInvestment: 6 },
        popularityEffect: 1,
        immediateFeedback: '+6 Md€/an de co-investissement — effet de productivité différé.',
      },
      {
        id: 'targeted-participation',
        title: 'PARTICIPATION CIBLÉE',
        description: 'Une participation limitée.',
        fiscalEffect: 2,
        economicPolicyEffect: { researchInvestment: 2 },
        popularityEffect: 0.5,
        immediateFeedback: '+2 Md€/an, participation limitée.',
      },
      {
        id: 'decline',
        title: 'DÉCLINER',
        description: 'Ne pas participer.',
        popularityEffect: -0.5,
        immediateFeedback: 'La France reste en retrait de ce plan.',
      },
    ],
  },
  {
    id: 'defense-pressure',
    title: 'LES ALLIÉS DEMANDENT UN EFFORT DE DÉFENSE',
    category: 'SECURITY',
    description: 'Les partenaires internationaux de la France demandent un effort de défense accru.',
    earliestTurn: 6,
    latestTurn: 26,
    baseProbability: 0.08,
    choices: [
      {
        id: 'increase-defense',
        title: 'AUGMENTER LE BUDGET DÉFENSE',
        description: 'Un signal fort envers les alliés.',
        fiscalEffect: 8,
        economicPolicyEffect: { currentSpendingChanges: 8 },
        popularityEffect: 0.5,
        immediateFeedback: '+8 Md€/an — un signal fort envers les alliés.',
      },
      {
        id: 'limited-reinforcement',
        title: 'RENFORCEMENT LIMITÉ',
        description: 'Un effort mesuré.',
        fiscalEffect: 3,
        economicPolicyEffect: { currentSpendingChanges: 3 },
        popularityEffect: 0.2,
        immediateFeedback: '+3 Md€/an, un effort mesuré.',
      },
      {
        id: 'refuse',
        title: 'REFUSER',
        description: 'Ne pas répondre à la demande.',
        popularityEffect: -0.5,
        immediateFeedback: 'Aucun effort supplémentaire — tension diplomatique limitée.',
      },
    ],
  },
  {
    id: 'tax-windfall',
    title: 'BONNE SURPRISE FISCALE',
    category: 'ECONOMY',
    description: 'Les recettes fiscales dépassent les prévisions.',
    earliestTurn: 4,
    latestTurn: 28,
    baseProbability: 0.08,
    exclusiveGroup: 'tax-revenue-surprise',
    conditions: (ctx) => ctx.gameState.economic.growth > ctx.gameState.economic.potentialGrowth,
    choices: [
      {
        id: 'spend-windfall',
        title: 'DÉPENSER LA MANNE',
        description: 'Utiliser la bonne surprise pour de nouvelles dépenses.',
        fiscalEffect: 5,
        economicPolicyEffect: { currentSpendingChanges: 5 },
        popularityEffect: 1.5,
        immediateFeedback: '+5 Md€/an de dépenses supplémentaires.',
      },
      {
        id: 'reduce-deficit',
        title: 'RÉDUIRE LE DÉFICIT',
        description: 'Laisser la bonne surprise améliorer les comptes.',
        popularityEffect: 0.5,
        immediateFeedback: 'La bonne surprise vient réduire le déficit.',
      },
      {
        id: 'cut-taxes',
        title: 'BAISSER LES IMPÔTS',
        description: 'Rendre une partie de la manne aux ménages.',
        fiscalEffect: -3,
        economicPolicyEffect: { householdTaxImpulse: -3 },
        popularityEffect: 1,
        immediateFeedback: '-3 Md€/an de recettes rendues aux ménages.',
      },
    ],
  },
  {
    id: 'tax-shortfall',
    title: 'MAUVAISE SURPRISE FISCALE',
    category: 'ECONOMY',
    description: 'Les recettes fiscales déçoivent, sous l’effet d’une conjoncture plus faible que prévu.',
    earliestTurn: 4,
    latestTurn: 28,
    baseProbability: 0.08,
    exclusiveGroup: 'tax-revenue-surprise',
    conditions: (ctx) => ctx.gameState.economic.growth <= ctx.gameState.economic.potentialGrowth,
    choices: [
      {
        id: 'borrow',
        title: 'EMPRUNTER',
        description: 'Financer le manque à gagner par la dette.',
        popularityEffect: 0,
        immediateFeedback: 'Le manque à gagner est financé par la dette.',
      },
      {
        id: 'cut-spending',
        title: 'RÉDUIRE LES DÉPENSES',
        description: 'Compenser par des économies.',
        fiscalEffect: -5,
        economicPolicyEffect: { currentSpendingChanges: -5 },
        popularityEffect: -1.5,
        immediateFeedback: '-5 Md€/an d’économies.',
      },
      {
        id: 'temporary-tax',
        title: 'MESURE FISCALE TEMPORAIRE',
        description: 'Une hausse ciblée et temporaire des recettes.',
        fiscalEffect: 3,
        economicPolicyEffect: { householdTaxImpulse: 3 },
        popularityEffect: -2,
        immediateFeedback: '+3 Md€/an de recettes supplémentaires.',
      },
    ],
  },
  {
    id: 'political-crisis',
    title: 'LA MAJORITÉ SE FISSURE',
    category: 'POLITICAL',
    description: 'Les tensions internes à la majorité menacent la stabilité du gouvernement.',
    earliestTurn: 8,
    latestTurn: 29,
    baseProbability: 0.1,
    conditions: (ctx) => ctx.governmentTension > 55 || ctx.politicalCapital < 20,
    probabilityModifier: (ctx) => (ctx.governmentTension > 75 ? 2 : 1),
    choices: [
      {
        id: 'reshuffle',
        title: 'REMANIEMENT MINISTÉRIEL',
        description: 'Un remaniement pour apaiser les tensions internes.',
        governmentTensionEffect: -20,
        popularityEffect: 1,
        politicalCapitalEffect: -2,
        immediateFeedback: 'Un remaniement apaise temporairement les tensions.',
      },
      {
        id: 'coalition-concessions',
        title: 'CONCESSIONS À LA COALITION',
        description: 'Des concessions pour préserver la majorité.',
        governmentTensionEffect: -10,
        politicalCapitalEffect: -4,
        immediateFeedback: 'Des concessions accordées pour préserver la majorité.',
      },
      {
        id: 'continue-unchanged',
        title: 'CONTINUER SANS CHANGEMENT',
        description: 'Ne rien changer.',
        governmentTensionEffect: 8,
        popularityEffect: -1,
        immediateFeedback: 'Aucun geste — la fracture persiste.',
        riskDescription: 'Aucune amélioration ne le résoudra sans le geste.',
      },
    ],
  },
]

export function getEventDefinition(id: string): EventDefinition {
  const event = EVENT_CATALOG.find((e) => e.id === id)
  if (!event) throw new Error(`Unknown event: ${id}`)
  return event
}
